server:
   port: 9080
   sessionTimeout: 30

spring:
   view:
    prefix: /WEB-INF
    suffix: .html
   jpa:
     hibernate:
       ddl-auto: create-drop

security:
   basic:
     enabled: false       
       
# Tomcat
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  backgroundProcessorDelay: 30